# Generated by Django 2.1.4 on 2019-01-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='username',
            new_name='user',
        ),
    ]
