# Generated by Django 2.1.4 on 2019-01-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0004_auto_20190112_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
