# Generated by Django 2.1.4 on 2019-01-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0005_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
