# Generated by Django 2.1.4 on 2019-01-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0006_remove_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
