# Generated by Django 2.1.4 on 2019-01-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0007_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
